//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByticHealth.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BHDBEntities : DbContext
    {
        public BHDBEntities()
            : base("name=BHDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billee> Billees { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PrimaryInsurance> PrimaryInsurances { get; set; }
        public virtual DbSet<Relative> Relatives { get; set; }
        public virtual DbSet<SecondaryInsurance> SecondaryInsurances { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    }
}
