//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByticHealth.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billee()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public decimal BilleeID { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string HomePhone { get; set; }
        public Nullable<bool> IsPatient { get; set; }
        public Nullable<bool> IsCoveredByInsurance { get; set; }
        public Nullable<decimal> PrimaryInsuranceID { get; set; }
        public Nullable<decimal> SecondaryInsuranceID { get; set; }
    
        public virtual PrimaryInsurance PrimaryInsurance { get; set; }
        public virtual SecondaryInsurance SecondaryInsurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
