//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByticHealth.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public decimal PatNum { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<bool> IsLegalName { get; set; }
        public string LegalName { get; set; }
        public string FormerName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SSN { get; set; }
        public string HomePhoneNo { get; set; }
        public string CellPhone { get; set; }
        public string Occupation { get; set; }
        public Nullable<decimal> EmployerID { get; set; }
        public string Referral { get; set; }
        public Nullable<bool> ReferredByDoctor { get; set; }
        public Nullable<decimal> BilleeID { get; set; }
        public Nullable<decimal> PrimaryInsuranceID { get; set; }
        public string OtherPrimaryInsurance { get; set; }
        public Nullable<decimal> SecondaryInsuranceID { get; set; }
        public Nullable<decimal> RelativeID { get; set; }
        public byte[] Signature { get; set; }
        public byte[] PassportPhoto { get; set; }
        public byte[] Barcode { get; set; }
        public Nullable<decimal> StaffID { get; set; }
        public Nullable<decimal> StaffCategoryID { get; set; }
    
        public virtual Billee Billee { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual PrimaryInsurance PrimaryInsurance { get; set; }
        public virtual Relative Relative { get; set; }
        public virtual SecondaryInsurance SecondaryInsurance { get; set; }
    }
}
