//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByticHealth.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondaryInsurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecondaryInsurance()
        {
            this.Billees = new HashSet<Billee>();
            this.Patients = new HashSet<Patient>();
        }
    
        public decimal SecondaryInsuranceID { get; set; }
        public string InsuranceName { get; set; }
        public string SubscriberName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string GroupNo { get; set; }
        public string PolicyNo { get; set; }
        public string RelationshipToPatient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billee> Billees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
